{% set name = "IGV" %}
{% set version = "2.17.0" %}
{% set sha256 = "7d5ba27937db2b05eb580e771a8d2902ea29e1d5e07be598ce2dfdaacb2a4af9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/igvteam/igv/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage('igv', max_pin="x") }}

requirements:
  build:
    - openjdk 11
  run:
    - openjdk 11

test:
  commands:
    - igv --version
    - igv_hidpi --version

about:
  home: http://www.broadinstitute.org/software/igv/home
  license: MIT
  license_family: MIT
  license_file: license.txt
  summary: |
    Integrative Genomics Viewer. Fast, efficient, scalable visualization tool for genomics
    data and annotations.

extra:
  identifiers:
    - biotools:igv
